spring:
  application:
    name: RabbitMQProducer

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8079

rabbitmq:
  queue:
    name: multiple_server_queue
  exchange:
    name: multiple_server_exchange
  routing:
    key: multiple_server_key