spring:
  application:
    name: RabbitMQConsumer2

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8082

rabbitmq:
  queue:
    name: multiple_server_queue
  exchange:
    name: multiple_server_exchange
  routing:
    key: multiple_server_key